package spec

// ChecksumEntry is a single line in checksums.txt: a SHA-256 digest paired with a file path.
type ChecksumEntry struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

// PackageManifest is the model for the manifest.json file embedded in a packaged skill artifact.
// It mirrors schemas/package-manifest.schema.json and is generated by skpm during packaging.
// Do not author this file manually.
type PackageManifest struct {
	SpecVersion    int               `json:"spec_version"`
	Name           string            `json:"name"`
	Namespace      string            `json:"namespace,omitempty"`
	Version        string            `json:"version"`
	Description    string            `json:"description,omitempty"`
	Entrypoint     string            `json:"entrypoint,omitempty"`
	CompatibleWith []Platform        `json:"compatible_with,omitempty"`
	PackageType    string            `json:"package_type"`
	SHA256         string            `json:"sha256,omitempty"`
	Files          []string          `json:"files,omitempty"`
	PackagedBy     string            `json:"packaged_by,omitempty"`
	PackagedAt     string            `json:"packaged_at,omitempty"`
	SourceCommit   string            `json:"source_commit,omitempty"`
	License        string            `json:"license,omitempty"`
	Signature      string            `json:"signature,omitempty"`
	Provenance     string            `json:"provenance,omitempty"`
	Metadata       map[string]string `json:"metadata,omitempty"`
}
